[workspace]
authors = ["Andrei Guliaev <andrei.guliaev@scilifelab.uu.se>"]
channels = ["bioconda", "conda-forge"]
name = "TwiMM"
platforms = ["linux-64", "osx-arm64"]
version = "1.6.0"

[tasks]
precom = "PYTHONPATH=. pre-commit run pytest-check --all-files"
tests = "PYTHONPATH=. pytest .tests/unit/"
precom-fmt = "pre-commit run snakefmt"
fmt-wf = "snakefmt -l 130 workflow/"
fmt-py="snakefmt -l 130 workflow/scripts/"
fmt-tests="snakefmt -l 130 .tests/unit/"
all-dry = "snakemake --configfile config/config.yaml -n --cores 1"
all-full = "snakemake --configfile config/config.yaml --profile profiles/marvin_cpu"
test-dry = "snakemake --configfiles config/config.yaml config/config_test.yaml -n --cores 1"
test-full = "snakemake --configfiles config/config.yaml config/config_test.yaml --profile profiles/marvin_cpu"
ruleg = "snakemake --configfiles config/config.yaml config/config_test.yaml --rulegraph | dot -Tsvg > images/rulegraph.svg"
dot = "snakemake --configfiles config/config.yaml config/config_test.yaml --rulegraph > images/rulegraph.dot"

# shared conda dependencies
[dependencies]
python = "3.9.*"
pycodestyle = ">=2.14.0,<3"
pytest = ">=8.4.1,<9"
snakefmt = ">=0.11.0,<0.12"
pre-commit = ">=4.3.0,<5"
pytest-cov = ">=6.2.1,<7"
pandas = ">=2.3.1,<3"
pulp = "<2.8"
tabulate = ">=0.9.0,<0.10"
snakemake-wrapper-utils = ">=0.8.0,<0.9"
networkx = ">=3.2.1,<4"
xlsxwriter = ">=3.2.5,<4"

# linux only
[target.linux-64.dependencies]
drmaa = "==0.7.9,<0.8"
python-graphviz = ">=0.16,<0.17"

[target.osx-arm64.dependencies]
pysam = ">=0.23.3,<0.24"

# shared PyPI dependencies
[pypi-dependencies]
snakemake = ">=7.32.4, <8"
setuptools = "*"
jinja2 = "<3.1.0"
mkdocs = "==1.4.2"
pymdown-extensions = "==9.10"
mkdocs-schema-reader = "==0.11.1"
mkdocs-simple-hooks = "==0.1.5"
mdx-spanner = "==0.0.5"
mkdocs-yaml-schema-plugin = "==0.2.3"
mkdocs-snakemake-rule-plugin = "==0.3.3"
mkdocs-material = "==9.1.7"

# hydra-genetics 3.x / Snakemake 7 environment (default)
[feature.hg3.pypi-dependencies]
hydra-genetics = "==3.3.2"

# hydra-genetics 4.x / Snakemake 7 environment
[feature.hg4.pypi-dependencies]
hydra-genetics = "==4.0.0"

[environments]
default = { features = ["hg4"], solve-group = "hg4" }
hg3 = { features = ["hg3"], solve-group = "hg3" }
