[workspace]
authors = ["Andrei Guliaev <andrei.guliaev@scilifelab.uu.se>"]
channels = ["bioconda", "conda-forge"]
name = "TwiMM"
platforms = ["linux-64"]
version = "1.6.0"

[tasks]
pre-commit = "PYTHONPATH=. pre-commit run pytest-check --all-files"
tests = "PYTHONPATH=. pytest .tests/unit/"
pc-snakefmt = "pre-commit run snakefmt"
snakefmt = "snakefmt -l 130 workflow/Snakefile"
all-dry-v1 = "snakemake --configfile config/config.yaml -n --cores 1"
all-full-v1 = "snakemake --configfile config/config.yaml --profile profiles/marvin_cpu"
test-dry-v2 = "snakemake --configfiles config/config.yaml config/design2/config_v2.yaml config/design2/config_test_v2.yaml -n --cores 1"
test-full-v2 = "snakemake --configfiles config/config.yaml config/design2/config_v2.yaml config/design2/config_test_v2.yaml --profile profiles/marvin_cpu"
all-dry-v2 = "snakemake --configfiles config/config.yaml config/design2/config_v2.yaml -n --cores 1"
all-full-v2 = "snakemake --configfiles config/config.yaml config/design2/config_v2.yaml --profile profiles/marvin_cpu"
rulegraph-cl = "snakemake --configfiles config/config.yaml config/design2/config_v2.yaml config/design2/config_test_v2.yaml --rulegraph | dot -Tsvg > images/rulegraph_clairs.svg"
rulegraph-ds = "snakemake --configfiles config/config.yaml config/design2/config_v2.yaml config/design2/config_test_v2.yaml --rulegraph | dot -Tsvg > images/rulegraph_deepsomatic.svg"

[dependencies]
python = "==3.10"
pycodestyle = ">=2.14.0,<3"
pytest = ">=8.4.1,<9"
snakefmt = ">=0.11.0,<0.12"
pre-commit = ">=4.3.0,<5"
pytest-cov = ">=6.2.1,<7"
pandas = ">=2.3.1,<3"
pulp = "<2.8"
drmaa = "==0.7.9"
tabulate = ">=0.9.0,<0.10"
snakemake-wrapper-utils = ">=0.8.0,<0.9"
networkx = ">=3.4.2,<4"
xlsxwriter = ">=3.2.9,<4"

[pypi-dependencies]
hydra-genetics = ">=3.3.0, <4"
jinja2 = "<3.1.0"
mkdocs = "==1.4.2"
pymdown-extensions = "==9.10"
mkdocs-schema-reader = "==0.11.1"
mkdocs-simple-hooks = "==0.1.5"
mdx-spanner = "==0.0.5"
mkdocs-yaml-schema-plugin = "==0.2.3"
mkdocs-snakemake-rule-plugin = "==0.3.3"
mkdocs-material = "==9.1.7"
