---
output: "config/output_files.yaml"
resources: "config/resources.yaml"
samples: "config/samples.tsv"
units: "config/units.tsv"

default_container: "docker://hydragenetics/common:3.3.0"
pipeline_version: "v1.4.0"

reference:
  fasta: "ref_data/GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta"
  fai: "ref_data/GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta.fai"
  trf: "ref_data/human_GRCh38_no_alt_analysis_set.trf.bed"
  design_bed: "ref_data/Myelom_expected_coverage_annotated_Oct2024.bed"

aligner: "pbmm2"
haplotag_path: "snv_indels/whatshap_haplotag"
haplotag_suffix: "haplotagged"

annotate_cnv:
  tag: "germline"
  germline: "ref_data/panel_full_genes.bed"

bcftools_filter_include_region:
  panel: "ref_data/Myelom_expected_coverage_annotated_Oct2024.bed"

bcftools_view:
  extra: ""

caller: "cnvkit"

clairs_to_call:
  container: "docker://hkubal/clairs-to:latest"
  extra: ""
  platform: "hifi_revio"

cnv_html_report:
  show_table: true
  cytobands: false

cnvkit_batch:
  container: "docker://hydragenetics/cnvkit:0.9.11"
  normal_reference: "ref_data/cnvkit.PoN.cnn"
  method: "hybrid"

cnvkit_call:
  container: "docker://hydragenetics/cnvkit:0.9.11"
  extra: ""
  purity: 0.9

cnvkit_vcf:
  container: "docker://hydragenetics/cnvkit:0.9.9"
  extra: ""

compile_xlsx_report:
  filters: "config/filters/config_vcf_report.yaml"
  genes: "ref_data/panel_full_genes.bed"

deepsomatic_t_only:
  container: "docker://google/deepsomatic:1.9.0"
  model: "PACBIO"
  pon: "../build_pon/results/bcftools_merge/normal_db.vcf.gz"
  extra: ""

filter_vcf:
  germline: "config/filters/config_hard_filter_germline_vep.yaml"

general_report: "config/report.yaml"

merge_cnv_json:
  germline_vcf: "snv_indels/whatshap_phase/{sample}_T.phased.include.panel.vep_annotated.filter.germline.bcftools_view.germline.vcf.gz"
  unfiltered_cnv_vcfs:
    - "cnv_sv/cnvkit_vcf/{sample}_T.pathology.annotate_cnv.germline.vcf.gz"
  filtered_cnv_vcfs:
    - "cnv_sv/cnvkit_vcf/{sample}_T.pathology.annotate_cnv.germline.vcf.gz"
  annotations:
    - "ref_data/Myelom_expected_coverage_annotated_Oct2024_genes_only.bed"

mosdepth:
  container: "docker://hydragenetics/mosdepth:0.3.6"
  by: "ref_data/Myelom_expected_coverage_annotated_Oct2024.bed"
  extra: ""

multiqc:
  container: "docker://hydragenetics/multiqc:1.25.1"
  reports:
    DNA:
      included_unit_types: 
        - "T"
      qc_files:
        - "qc/sequali/{sample}_{type}_{processing_unit}_{barcode}.json"
        - "qc/mosdepth/{sample}_{type}.mosdepth.global.dist.txt"
        - "qc/mosdepth/{sample}_{type}.mosdepth.region.dist.txt"
        - "qc/mosdepth/{sample}_{type}.mosdepth.summary.txt"

pbmarkdup:
  container: "docker://hydragenetics/pbmarkdup:1.1.0"
  extra: " --ignore-read-names"

pbmm2_index:
  container: "docker://hydragenetics/pbmm2:1.16"
  preset: "HIFI"
  extra: ""

pbmm2_align:
  container: "docker://hydragenetics/pbmm2:1.16"
  preset: "HIFI"
  extra: ""

pbmm2_merge:
  container: "docker://hydragenetics/pbmm2:1.16"

sequali:
  container: "docker://hydragenetics/sequali:0.12.0"
  extra: ""

sniffles2_call:
  container: "docker://hydragenetics/sniffles2:2.6.1"
  extra: ""

svdb_merge:
  tc_method:
    - name: pathology
      cnv_caller:
        - cnvkit

trimmer_software: "None"

use_deepsomatic: false

vep:
  container: "docker://hydragenetics/vep:113.0"
  vep_cache: "/data/ref_genomes/VEP"
  mode: "--offline --cache "
  extra: " --assembly GRCh38 --pick --cache_version 110 --variant_class --refseq --protein --hgvs --fasta {fasta}"

whatshap_phase:
  container: "docker://hydragenetics/whatshap:2.2"
  extra: " --ignore-read-groups"

whatshap_haplotag:
  container: "docker://hydragenetics/whatshap:2.2"
  extra: " --ignore-read-groups --skip-missing-contigs"
