---

 files:
   - name: "snv_vep_annotated_vcf"
     output: "results/snv_indels/whatshap_phase/{sample}_T.phased.include.panel.vep_annotated.vcf.gz"
     input: "snv_indels/whatshap_phase/{sample}_T.phased.include.panel.vep_annotated.vcf.gz"
   - name: "sniffles2_vcf"
     output: "results/cnv_sv/sniffles2/{sample}_T.include.panel.vcf.gz"
     input: "cnv_sv/sniffles2_call/{sample}_T.include.panel.vcf.gz"
   - name: "cnvkit_html_reports"
     output: "results/cnv_sv/cnvkit/html_reports/{sample}_{type}.pathology.cnv_report.html"
     input: "reports/cnv_html_report/{sample}_{type}.pathology.cnv_report.html"
   - name: "mapped_bam"
     output: "results/mapped_bam/whatshap_haplotag/{sample}_T.haplotagged.bam"
     input: "snv_indels/whatshap_haplotag/{sample}_T.haplotagged.bam"
   - name: "mapped_bam_index"
     output: "results/mapped_bam/whatshap_haplotag/{sample}_T.haplotagged.bam.bai"
     input: "snv_indels/whatshap_haplotag/{sample}_T.haplotagged.bam.bai"
   - name: "annotated_cnvkit_vcf"
     output: "results/cnv_sv/cnvkit/cnvkit_vcf/{sample}_T.pathology.annotate_cnv.germline.vcf"
     input: "cnv_sv/cnvkit_vcf/{sample}_T.pathology.annotate_cnv.germline.vcf"
   - name: "index_cnvkit_vcf"
     output: "results/cnv_sv/cnvkit/cnvkit_vcf/{sample}_T.pathology.annotate_cnv.germline.vcf.gz.tbi"
     input: "cnv_sv/cnvkit_vcf/{sample}_T.pathology.annotate_cnv.germline.vcf.gz.tbi"
   - name: "cnvkit_cnr"
     output: "results/cnv_sv/cnvkit/cnvkit_batch/{sample}_T.cnr"
     input: "cnv_sv/cnvkit_batch/{sample}/{sample}_T.cnr"
   - name: "cnvkit_cns"
     output: "results/cnv_sv/cnvkit_batch/{sample}_T.cns"
     input: "cnv_sv/cnvkit_batch/{sample}/{sample}_T.cns"
   - name: "combined_variants_xlsx"
     output: "results/xlsx_reports/{sample}_combined_report.xlsx"
     input: "reports/xlsx_reports/{sample}_combined_report.xlsx"
  #  - name: "multiqc_html_report"
  #    output: "results/qc/multiqc/multiqc_{report}.html"
  #    input: "qc/multiqc/multiqc_{report}.html"
  #  - name: "multiqc_html_data"
  #    output: "results/qc/multiqc/multiqc_{report}_data"
  #    input: "qc/multiqc/multiqc_{report}_data"