idid_min_len: 1000
snvs_remove:
  - "intergenic_variant"
  - "NMD_transcript_variant"
  - "non_coding_transcript_variant"
  - "upstream_gene_variant"
  - "downstream_gene_variant"
  - "TFBS_ablation"
  - "TFBS_amplification"
  - "TF_binding_site_variant"
  - "regulatory_region_ablation"
  - "regulatory_region_amplification"
  - "regulatory_region_variant"
  - "intron_variant"
  - "intron_variant&non_coding_transcript_variant"
# must match FORMAT fields
format_fields:
  - "GT"
  - "GQ"
  - "DP"
  - "AD"
  - "AF"
columns_keep_snv:
  - "CHROM"
  - "POS"
  - "REF"
  - "ALT"
  - "Consequence"
  - "SYMBOL"
  - "Feature"
  - "EXON"
  - "INTRON"
  - "HGVSc"
  - "HGVSp"
  - "AF"
  - "DP"
  - "AD"
columns_drop_tn:
  - "END"
  - "SVLEN"
  - "GENOTYPE"
  - "GENOME QUALITY"
columns_drop_idid:
  - "GENOTYPE"
  - "GENOME QUALITY"
# must match present VEP annotation fields
vep_info_fields:
  - "Allele"
  - "Consequence"
  - "IMPACT"
  - "SYMBOL"
  - "Gene"
  - "Feature_type"
  - "Feature"
  - "BIOTYPE"
  - "EXON"
  - "INTRON"
  - "HGVSc"
  - "HGVSp"
  - "cDNA_position"
  - "CDS_position"
  - "Protein_position"
  - "Amino_acids"
  - "Codons"
  - "Existing_variation"
  - "DISTANCE"
  - "STRAND"
  - "FLAGS"
  - "VARIANT_CLASS"
  - "SYMBOL_SOURCE"
  - "HGNC_ID"
  - "ENSP"
  - "REFSEQ_MATCH"
  - "REFSEQ_OFFSET"
  - "GIVEN_REF"
  - "USED_REF"
  - "BAM_EDIT"
  - "HGVS_OFFSET"
